// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Akademi")]
public partial class Akademi : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return AkademiId; }
        set { AkademiId = value; }
    }

    [Key]
    [Column("AkademiID")]
    public int AkademiId { get; set; }

    [Required]
    [StringLength(100)]
    public string AkademiNavn { get; set; }

    [StringLength(500)]
    public string Beskrivelse { get; set; }

    [Required]
    [StringLength(200)]
    public string AkademiAdresse { get; set; }

    [Required]
    [StringLength(100)]
    public string AkademiLokation { get; set; }

    public int? AntalLærere { get; set; }

    [InverseProperty("Akademi")]
    public virtual ICollection<HukommelseRam> HukommelseRams { get; set; } = new List<HukommelseRam>();

    [InverseProperty("Akademi")]
    public virtual ICollection<Lærere> Læreres { get; set; } = new List<Lærere>();

    [InverseProperty("Akademi")]
    public virtual ICollection<Studieleder> Studieleders { get; set; } = new List<Studieleder>();

    [InverseProperty("Akademi")]
    public virtual ICollection<Uddannelse> Uddannelses { get; set; } = new List<Uddannelse>();
    
}