// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Fag")]
public partial class Fag : IHarId
{
    [NotMapped]
    public int Id 
    {
        get { return FagId; }
        set { FagId = value; }
    }

    [Key]
    [Column("FagID")]
    public int FagId { get; set; }

    [Required]
    [StringLength(100)]
    public string FagNavn { get; set; }

    [Column("UddannelseID")]
    public int UddannelseId { get; set; }

    [InverseProperty("Fag")]
    public virtual ICollection<HukommelseRam> HukommelseRams { get; set; } = new List<HukommelseRam>();

    [InverseProperty("Fag")]
    public virtual ICollection<Kompetencer> Kompetencers { get; set; } = new List<Kompetencer>();

    [ForeignKey("UddannelseId")]
    [InverseProperty("Fags")]
    public virtual Uddannelse Uddannelse { get; set; }
}