// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Fag")]
public partial class Fag : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return FagId; }
        set { FagId = value; }
    }

    [Key]
    [Column("FagID")]
    public int FagId { get; set; }

    [StringLength(100)]
    public string FagNavn { get; set; }

    [StringLength(250)]
    public string FagBeskrivelse { get; set; }

    [InverseProperty("Fag")]
    public virtual ICollection<Kompetence> Kompetences { get; set; } = new List<Kompetence>();

    [InverseProperty("Fag")]
    public virtual ICollection<UddannelseOgFagAllokering> UddannelseOgFagAllokerings { get; set; } = new List<UddannelseOgFagAllokering>();
}