// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("HukommelseRAM")]
public partial class HukommelseRam : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return HukommelseRamid; }
        set { HukommelseRamid = value; }
    }
    [Key]
    [Column("HukommelseRAMID")]
    public int HukommelseRamid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Kalender { get; set; }

    [Column("AkademiID")]
    public int AkademiId { get; set; }

    [Column("UddannelseID")]
    public int UddannelseId { get; set; }

    [Column("FagID")]
    public int FagId { get; set; }

    [Column("LærerID")]
    public int LærerId { get; set; }

    [Column("KompetenceID")]
    public int KompetenceId { get; set; }

    [ForeignKey("AkademiId")]
    [InverseProperty("HukommelseRams")]
    public virtual Akademi Akademi { get; set; }

    [ForeignKey("FagId")]
    [InverseProperty("HukommelseRams")]
    public virtual Fag Fag { get; set; }

    [ForeignKey("KompetenceId")]
    [InverseProperty("HukommelseRams")]
    public virtual Kompetencer Kompetence { get; set; }

    [ForeignKey("LærerId")]
    [InverseProperty("HukommelseRams")]
    public virtual Lærere Lærer { get; set; }

    [ForeignKey("UddannelseId")]
    [InverseProperty("HukommelseRams")]
    public virtual Uddannelse Uddannelse { get; set; }
}