// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Kompetence")]
public partial class Kompetence : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return KompetenceId; }
        set { KompetenceId = value; }
    }

    [Key]
    [Column("KompetenceID")]
    public int KompetenceId { get; set; }

    [StringLength(100)]
    public string KompetenceNavn { get; set; }

    [StringLength(250)]
    public string KompetenceBeskrivelse { get; set; }

    [Column("FagID")]
    public int? FagId { get; set; }

    [ForeignKey("FagId")]
    [InverseProperty("Kompetences")]
    public virtual Fag Fag { get; set; }

    [InverseProperty("Kompetence")]
    public virtual ICollection<LærerOgKompetenceAllokering> LærerOgKompetenceAllokerings { get; set; } = new List<LærerOgKompetenceAllokering>();
}