// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Lærere")]
[Index("Email", Name = "UQ__Lærere__A9D10534C4CE4FAA", IsUnique = true)]
public partial class Lærere : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return LærerId; }
        set { LærerId = value; }
    }

    [Key]
    [Column("LærerID")]
    public int LærerId { get; set; }

    [Required]
    [StringLength(255)]
    public string Adgangskode { get; set; }

    [Required]
    [StringLength(100)]
    public string Navn { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Telefonnummer { get; set; }

    [Required]
    [StringLength(50)]
    public string Ansættelsesform { get; set; }

    public int? Timetal { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(100)]
    public string Hjemmeplacering { get; set; }

    [StringLength(100)]
    public string Primærplacering { get; set; }

    [Column("AkademiID")]
    public int AkademiId { get; set; }

    [ForeignKey("AkademiId")]
    [InverseProperty("Læreres")]
    public virtual Akademi Akademi { get; set; }

    [InverseProperty("Lærer")]
    public virtual ICollection<HukommelseRam> HukommelseRams { get; set; } = new List<HukommelseRam>();
}