// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Lærer")]
[Index("Email", Name = "UQ__Lærer__A9D105344FC838BB", IsUnique = true)]
public partial class Lærer : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return LærerId; }
        set { LærerId = value; }
    }

    [Key]
    [Column("LærerID")]
    public int LærerId { get; set; }

    [StringLength(100)]
    public string Navn { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Telefonnummer { get; set; }

    [StringLength(255)]
    public string Adgangskode { get; set; }

    [StringLength(50)]
    public string Ansættelsesform { get; set; }

    public int? Timetal { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(100)]
    public string Hjemmeplacering { get; set; }

    [StringLength(100)]
    public string Primærplacering { get; set; }

    [StringLength(255)]
    public string Sekundaereplaceringer { get; set; }

    [StringLength(255)]
    public string FagligeKvalifikationer { get; set; }

    [StringLength(255)]
    public string PædagogiskeKvalifikationer { get; set; }

    [StringLength(255)]
    public string SpecielleKvalifikationer { get; set; }

    [StringLength(255)]
    public string SemesterErfaring { get; set; }

    [StringLength(255)]
    public string Beviser { get; set; }

    [InverseProperty("Lærer")]
    public virtual ICollection<LærerOgKompetenceAllokering> LærerOgKompetenceAllokerings { get; set; } = new List<LærerOgKompetenceAllokering>();

    [InverseProperty("Lærer")]
    public virtual ICollection<UddannelseOgLærerAllokering> UddannelseOgLærerAllokerings { get; set; } = new List<UddannelseOgLærerAllokering>();
}