// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Studieleder")]
[Index("Email", Name = "UQ__Studiele__A9D1053410D175AA", IsUnique = true)]
public partial class Studieleder : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return StudielederId; }
        set { StudielederId = value; }
    }

    [Key]
    [Column("StudielederID")]
    public int StudielederId { get; set; }

    [StringLength(100)]
    public string Navn { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Telefon { get; set; }

    [StringLength(255)]
    public string Adgangskode { get; set; }

    [Column("AkademiID")]
    public int? AkademiId { get; set; }

    [ForeignKey("AkademiId")]
    [InverseProperty("Studieleders")]
    public virtual Akademi Akademi { get; set; }
  

}