// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("UddannelseOgLærerAllokering")]
public partial class UddannelseOgLærerAllokering : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return Uolaid; }
        set { Uolaid = value; }
    }

    [Key]
    [Column("UOLAid")]
    public int Uolaid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SlutTid { get; set; }

    [Column("UOLABeskrivelse")]
    [StringLength(250)]
    public string Uolabeskrivelse { get; set; }

    [Column("UddannelseID")]
    public int? UddannelseId { get; set; }

    [Column("LærerID")]
    public int? LærerId { get; set; }

    [ForeignKey("LærerId")]
    [InverseProperty("UddannelseOgLærerAllokerings")]
    public virtual Lærer Lærer { get; set; }

    [ForeignKey("UddannelseId")]
    [InverseProperty("UddannelseOgLærerAllokerings")]
    public virtual Uddannelse Uddannelse { get; set; }
}