// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("Uddannelse")]
public partial class Uddannelse : IHarId

{
    [NotMapped]
    public int Id     {
        get { return UddannelseId; }
        set { UddannelseId = value; }
    }

    [Key]
    [Column("UddannelseID")]
    public int UddannelseId { get; set; }

    [Required]
    [StringLength(100)]
    public string UddannelseNavn { get; set; }

    [StringLength(500)]
    public string Beskrivelse { get; set; }

    public int Semester { get; set; }

    [StringLength(50)]
    public string Lokale { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Kalender { get; set; }

    [Column("AkademiID")]
    public int AkademiId { get; set; }

    [ForeignKey("AkademiId")]
    [InverseProperty("Uddannelses")]
    public virtual Akademi Akademi { get; set; }

    [InverseProperty("Uddannelse")]
    public virtual ICollection<Fag> Fags { get; set; } = new List<Fag>();

    [InverseProperty("Uddannelse")]
    public virtual ICollection<HukommelseRam> HukommelseRams { get; set; } = new List<HukommelseRam>();
}