// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

[Table("UddannelseOgFagAllokering")]
public partial class UddannelseOgFagAllokering : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return Uofaid; }
        set { Uofaid = value; }
    }

    [Key]
    [Column("UOFAid")]
    public int Uofaid { get; set; }

    [Column("UOFAidBeskrivelse")]
    [StringLength(250)]
    public string UofaidBeskrivelse { get; set; }

    [Column("UddannelseID")]
    public int? UddannelseId { get; set; }

    [Column("FagID")]
    public int? FagId { get; set; }

    [ForeignKey("FagId")]
    [InverseProperty("UddannelseOgFagAllokerings")]
    public virtual Fag Fag { get; set; }

    [ForeignKey("UddannelseId")]
    [InverseProperty("UddannelseOgFagAllokerings")]
    public virtual Uddannelse Uddannelse { get; set; }
}