// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFCZealand.Models;

public partial class ZealandDBContext : DbContext
{
    public ZealandDBContext()
    {
    }
    public ZealandDBContext(DbContextOptions<ZealandDBContext> options)
        : base(options)
    {
    }
    public virtual DbSet<Akademi> Akademis { get; set; }

    public virtual DbSet<Fag> Fags { get; set; }

    public virtual DbSet<HukommelseRam> HukommelseRams { get; set; }

    public virtual DbSet<Kompetencer> Kompetencers { get; set; }

    public virtual DbSet<Lærere> Læreres { get; set; }

    public virtual DbSet<Studieleder> Studieleders { get; set; }

    public virtual DbSet<Uddannelse> Uddannelses { get; set; }


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=ZealandDB;Integrated Security=True;Encrypt=True");


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Akademi>(entity =>
        {
            entity.HasKey(e => e.AkademiId).HasName("PK__Akademi__DA6D732E80A87704");

            entity.Property(e => e.AntalLærere).HasDefaultValue(0);
        });

        modelBuilder.Entity<Fag>(entity =>
        {
            entity.HasKey(e => e.FagId).HasName("PK__Fag__9A31300BEE3D2E9C");

            entity.HasOne(d => d.Uddannelse).WithMany(p => p.Fags)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Fag__UddannelseI__33D4B598");
        });

        modelBuilder.Entity<HukommelseRam>(entity =>
        {
            entity.HasKey(e => e.HukommelseRamid).HasName("PK__Hukommel__782821096A2FF677");

            entity.HasOne(d => d.Akademi).WithMany(p => p.HukommelseRams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hukommels__Akade__398D8EEE");

            entity.HasOne(d => d.Fag).WithMany(p => p.HukommelseRams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hukommels__FagID__3B75D760");

            entity.HasOne(d => d.Kompetence).WithMany(p => p.HukommelseRams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hukommels__Kompe__3D5E1FD2");

            entity.HasOne(d => d.Lærer).WithMany(p => p.HukommelseRams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hukommels__Lærer__3C69FB99");

            entity.HasOne(d => d.Uddannelse).WithMany(p => p.HukommelseRams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hukommels__Uddan__3A81B327");
        });

        modelBuilder.Entity<Kompetencer>(entity =>
        {
            entity.HasKey(e => e.KompetenceId).HasName("PK__Kompeten__C03DB505A9DEFA5B");

            entity.HasOne(d => d.Fag).WithMany(p => p.Kompetencers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Kompetenc__FagID__36B12243");
        });

        modelBuilder.Entity<Lærere>(entity =>
        {
            entity.HasKey(e => e.LærerId).HasName("PK__Lærere__60F459019D9A044A");

            entity.Property(e => e.Status).HasDefaultValue("Aktiv");
            entity.Property(e => e.Timetal).HasDefaultValue(0);

            entity.HasOne(d => d.Akademi).WithMany(p => p.Læreres)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Lærere__AkademiI__2A4B4B5E");
        });

        modelBuilder.Entity<Studieleder>(entity =>
        {
            entity.HasKey(e => e.StudielederId).HasName("PK__Studiele__ED5E959C00C1A58F");

            entity.HasOne(d => d.Akademi).WithMany(p => p.Studieleders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Studieled__Akade__30F848ED");
        });

        modelBuilder.Entity<Uddannelse>(entity =>
        {
            entity.HasKey(e => e.UddannelseId).HasName("PK__Uddannel__DA78925E8454601D");

            entity.HasOne(d => d.Akademi).WithMany(p => p.Uddannelses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Uddannels__Akade__2D27B809");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}