// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text.Json;

namespace EFCZealand.Models;

public partial class ZealandDBContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
            optionsBuilder.UseSqlServer(
                JsonDocument.Parse(File.ReadAllText("appsettings.json"))
                    .RootElement.GetProperty("ConnectionStrings")
                    .GetProperty("LocalDB").GetString()); // Valg LocalDB eller ServerDB
    }
                    
    public ZealandDBContext()
    {
    }
    public ZealandDBContext(DbContextOptions<ZealandDBContext> options)
        : base(options)
    {
    }
    public virtual DbSet<Akademi> Akademis { get; set; }

    public virtual DbSet<Fag> Fags { get; set; }

    public virtual DbSet<Kompetence> Kompetences { get; set; }

    public virtual DbSet<Lærer> Lærers { get; set; }

    public virtual DbSet<LærerOgKompetenceAllokering> LærerOgKompetenceAllokerings { get; set; }

    public virtual DbSet<Studieleder> Studieleders { get; set; }

    public virtual DbSet<Uddannelse> Uddannelses { get; set; }

    public virtual DbSet<UddannelseOgFagAllokering> UddannelseOgFagAllokerings { get; set; }

    public virtual DbSet<UddannelseOgLærerAllokering> UddannelseOgLærerAllokerings { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Akademi>(entity =>
        {
            entity.HasKey(e => e.AkademiId).HasName("PK__Akademi__DA6D732EDB7E7069");

            entity.Property(e => e.AntalLærere).HasDefaultValue(0);
        });

        modelBuilder.Entity<Fag>(entity =>
        {
            entity.HasKey(e => e.FagId).HasName("PK__Fag__9A31300B59254135");
        });

        modelBuilder.Entity<Kompetence>(entity =>
        {
            entity.HasKey(e => e.KompetenceId).HasName("PK__Kompeten__C03DB50565161100");

            entity.HasOne(d => d.Fag).WithMany(p => p.Kompetences)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Kompetence_Fag");
        });

        modelBuilder.Entity<Lærer>(entity =>
        {
            entity.HasKey(e => e.LærerId).HasName("PK__Lærer__60F4590194E88B8A");

            entity.Property(e => e.Status).HasDefaultValue("Aktiv");
            entity.Property(e => e.Timetal).HasDefaultValue(0);
        });

        modelBuilder.Entity<LærerOgKompetenceAllokering>(entity =>
        {
            entity.HasKey(e => e.Lokaid).HasName("PK__LærerOgK__D84932828512A431");

            entity.HasOne(d => d.Kompetence).WithMany(p => p.LærerOgKompetenceAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LOKA_Kompetence");

            entity.HasOne(d => d.Lærer).WithMany(p => p.LærerOgKompetenceAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LOKA_Lærer");
        });

        modelBuilder.Entity<Studieleder>(entity =>
        {
            entity.HasKey(e => e.StudielederId).HasName("PK__Studiele__ED5E959C1AA16FA4");

            entity.HasOne(d => d.Akademi).WithMany(p => p.Studieleders)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Studieleder_Akademi");
        });

        modelBuilder.Entity<Uddannelse>(entity =>
        {
            entity.HasKey(e => e.UddannelseId).HasName("PK__Uddannel__DA78925EEC3304F6");

            entity.HasOne(d => d.Akademi).WithMany(p => p.Uddannelses)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Uddannelse_Akademi");
        });

        modelBuilder.Entity<UddannelseOgFagAllokering>(entity =>
        {
            entity.HasKey(e => e.Uofaid).HasName("PK__Uddannel__4E6A0B0F92A617EA");

            entity.HasOne(d => d.Fag).WithMany(p => p.UddannelseOgFagAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_UOFA_Fag");

            entity.HasOne(d => d.Uddannelse).WithMany(p => p.UddannelseOgFagAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_UOFA_Uddannelse");
        });

        modelBuilder.Entity<UddannelseOgLærerAllokering>(entity =>
        {
            entity.HasKey(e => e.Uolaid).HasName("PK__Uddannel__E84B41CC1DBB2E71");

            entity.HasOne(d => d.Lærer).WithMany(p => p.UddannelseOgLærerAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_UOLA_Laerer");

            entity.HasOne(d => d.Uddannelse).WithMany(p => p.UddannelseOgLærerAllokerings)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_UOLA_Uddannelse");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}